/* Generated By:JavaCC: Do not edit this line. SJaPParserTreeConstants.java Version 5.0 */
public interface SJaPParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTLINJER = 1;
  public int JJTLINJE = 2;
  public int JJTDCL_VAR = 3;
  public int JJTVARS = 4;
  public int JJTVARIABEL = 5;
  public int JJTTYPE = 6;
  public int JJTDCL_METODER = 7;
  public int JJTDCL_METODE = 8;
  public int JJTMETODE = 9;
  public int JJTOPERATION = 10;
  public int JJTTERM = 11;
  public int JJTIF_STATEMENT = 12;
  public int JJTELLERS_STATEMENT = 13;
  public int JJTWHILE_LOKKE = 14;
  public int JJTFOR_LOKKE = 15;
  public int JJTSTATS = 16;
  public int JJTSTAT = 17;
  public int JJTSAMMENLIGN = 18;
  public int JJTLIST_OF_VARS = 19;


  public String[] jjtNodeName = {
    "START",
    "LINJER",
    "LINJE",
    "DCL_VAR",
    "VARS",
    "VARIABEL",
    "TYPE",
    "DCL_METODER",
    "DCL_METODE",
    "METODE",
    "OPERATION",
    "TERM",
    "IF_STATEMENT",
    "ELLERS_STATEMENT",
    "WHILE_LOKKE",
    "FOR_LOKKE",
    "STATS",
    "STAT",
    "SAMMENLIGN",
    "LIST_OF_VARS",
  };
}
/* JavaCC - OriginalChecksum=da334752365a4f119423da408f188a60 (do not edit this line) */
