/* Generated By:JavaCC: Do not edit this line. SJaPParserTreeConstants.java Version 5.0 */
public interface SJaPParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTLINJER = 1;
  public int JJTLINJE = 2;
  public int JJTDCL_VAR = 3;
  public int JJTVARS = 4;
  public int JJTVARIABEL = 5;
  public int JJTTYPE = 6;
  public int JJTDCL_METODER = 7;
  public int JJTDCL_METODE = 8;
  public int JJTMETODE = 9;
  public int JJTOPERATION = 10;
  public int JJTTERM = 11;
  public int JJTIF_STATMENT = 12;
  public int JJTELLERS_STATMENT = 13;
  public int JJTWHILE_LOKKE = 14;
  public int JJTFOR_LOKKE = 15;
  public int JJTSTATS = 16;
  public int JJTSTAT = 17;
  public int JJTSAMMENLIGN = 18;
  public int JJTLIST_OF_VARS = 19;


  public String[] jjtNodeName = {
    "start",
    "linjer",
    "linje",
    "dcl_var",
    "vars",
    "variabel",
    "type",
    "dcl_metoder",
    "dcl_metode",
    "metode",
    "operation",
    "term",
    "if_statment",
    "ellers_statment",
    "while_lokke",
    "for_lokke",
    "stats",
    "stat",
    "sammenlign",
    "list_of_vars",
  };
}
/* JavaCC - OriginalChecksum=5f2d339767cdc65e83e38232d14f7a4d (do not edit this line) */
