/* Generated By:JavaCC: Do not edit this line. SJaPParserVisitor.java Version 5.0 */
public interface SJaPParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=cea96784173b62450655af67deb64a8d (do not edit this line) */
